# Lighthouse-Badger-Easy | GitHub Action Workflow
#
# Description: Generates, adds & updates manually/automatically Lighthouse badges & reports from one/multiple input URL(s) to the current repository & main branch with minimal settings
# Author: Sitdisch
# Source: https://github.com/myactionway/lighthouse-badger-workflows
# License: MIT
# Copyright (c) 2021 Sitdisch

name: "Lighthouse Badger"

########################################################################
# DEFINE YOUR INPUTS AND TRIGGERS IN THE FOLLOWING
########################################################################

# INPUTS as Secrets (env) for not manually triggered workflows
env:
  URLS: https://notajely.github.io # 确保这是你想要测试的正确 URL
  # If any of the following env is blank, a default value is used instead
  # REPO_BRANCH: 'main' # 不再需要这个env变量来定义分支，如果总是main
  MOBILE_LIGHTHOUSE_PARAMS: "--only-categories=performance,accessibility,best-practices,seo --throttling.cpuSlowdownMultiplier=2"
  DESKTOP_LIGHTHOUSE_PARAMS: "--only-categories=performance,accessibility,best-practices,seo --preset=desktop --throttling.cpuSlowdownMultiplier=1"

# TRIGGERS
on:
  page_build:
  # schedule: # Check your schedule here => https://crontab.guru/
  #   - cron: '55 23 * * 0' # e.g. every Sunday at 23:55
  #
  # THAT'S IT; YOU'RE DONE;
  workflow_dispatch:

########################################################################
# THAT'S IT; YOU DON'T HAVE TO DEFINE ANYTHING IN THE FOLLOWING
########################################################################

jobs:
  lighthouse-badger-easy:
    runs-on: ubuntu-latest
    timeout-minutes: 8
    permissions:
      contents: write
    steps:
      # Preparatory Tasks 不再需要，因为我们直接使用 'main' 分支和当前仓库
      # - name: Preparatory Tasks
      #   run: |
      #     REPOSITORY=`expr "${{ env.REPO_BRANCH }}" : "\([^ ]*\)"`
      #     BRANCH=`expr "${{ env.REPO_BRANCH }}" : ".* \([^ ]*\)"`
      #     echo "REPOSITORY=$REPOSITORY" >> $GITHUB_ENV
      #     echo "BRANCH=$BRANCH" >> $GITHUB_ENV
      #   env:
      #     REPO_BRANCH: ${{ env.REPO_BRANCH }}

      - name: Checkout main branch of current repository
        uses: actions/checkout@v4
        with:
          # repository: ${{ github.repository }} # 默认就是当前仓库，可以不写
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: "main" # 直接指定 'main' 分支

      - name: Checkout lighthouse-badges repository
        uses: actions/checkout@v4
        with:
          repository: "myactionway/lighthouse-badges"
          path: temp_lighthouse_badges_nested
          # token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Lighthouse Badger Action
        uses: myactionway/lighthouse-badger-action@v2.2
        with:
          urls: ${{ env.URLS }}
          mobile_lighthouse_params: ${{ env.MOBILE_LIGHTHOUSE_PARAMS }}
          desktop_lighthouse_params: ${{ env.DESKTOP_LIGHTHOUSE_PARAMS }}
          # repo_branch: 'main' # 如果action需要，明确指定

      # 如果 myactionway/lighthouse-badger-action 不会自动提交，则取消以下注释
      # - name: Commit and push Lighthouse badges
      #   if: ${{ github.event_name != 'pull_request' }}
      #   uses: stefanzweifel/git-auto-commit-action@v5
      #   with:
      #     commit_message: "Update Lighthouse badges"
      #     branch: 'main'
